apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mockoon
  name: mockoon
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mockoon
  type: NodePort
status:
  loadBalancer: {}
